<!--content-->

		<div class="footer">
		
		</div>
		<script src="<?php echo $js; ?>jquery-1.12.2.min.js" type="text/javascript"></script>
		<script src="<?php echo $js; ?>bootstrap.min.js" type="text/javascript"></script>
		<script src="<?php echo $js; ?>jquery-ui.min.js" type="text/javascript"></script>
		<script src="<?php echo $js; ?>jquery.selectBoxIt.min.js" type="text/javascript"></script>
		<script src="<?php echo $js; ?>back-end.js" type="text/javascript"></script>
		<script>
            // Java Script Functions
             
            // textarea resize responsively
            function auto_grow(element) {
                element.style.height = (element.scrollHeight)+"px";
            }
        </script>
	</body>
</html>